- fern-java-codegen-utils/src/main/java/com/fern/codegen/GeneratedFileWithDefinition.java
- fern-jersey-codegen/src/main/java/com/fern/services/jersey/codegen/GeneratedServiceWithDefinition.java
- fern-jersey-codegen/src/main/java/com/fern/services/jersey/codegen/ServiceGenerator.java
- fern-model-codegen/src/main/java/com/fern/model/codegen/Generator.java
- fern-model-codegen/src/main/java/com/fern/model/codegen/ModelGenerator.java
- fern-model-codegen/src/main/java/com/fern/model/codegen/alias/AliasGenerator.java
- fern-model-codegen/src/main/java/com/fern/model/codegen/alias/GeneratedAlias.java
- fern-model-codegen/src/main/java/com/fern/model/codegen/enums/EnumGenerator.java
- fern-model-codegen/src/main/java/com/fern/model/codegen/enums/GeneratedEnum.java
- fern-model-codegen/src/main/java/com/fern/model/codegen/interfaces/GeneratedInterface.java
- fern-model-codegen/src/main/java/com/fern/model/codegen/interfaces/InterfaceGenerator.java
- fern-model-codegen/src/main/java/com/fern/model/codegen/object/GeneratedObject.java
- fern-model-codegen/src/main/java/com/fern/model/codegen/object/ObjectGenerator.java
- fern-model-codegen/src/main/java/com/fern/model/codegen/union/GeneratedUnion.java
- fern-model-codegen/src/main/java/com/fern/model/codegen/union/UnionGenerator.java
- fern-model-codegen/src/test/java/com/fern/model/codegen/object/ObjectGeneratorTest.java
**Expected:** an immutables property like `String _class()` should have a static staged builder method with the signature: 
```java
static Immutable<Class>._classBuildStage builder() {
return Immutable<Class>.builder();
}
```
Instead we would generate 
```java
static Immutable<Class>.ClassBuildStage builder() {
return Immutable<Class>.builder();
}
```
which would fail to compile.
> improvement: fix static builder method generation w/ non alphabetic properties

- fern-model-codegen/src/main/java/com/fern/model/codegen/union/UnionGenerator.java
for a union object config like 
```java
MyObject: 
union: 
goal: Goal
```
we would generate an internal value class 
```java
@Value.Enclsoing
public final MyObject {
private final InternalValue;
interface InternalValue {
<T> T accept(Visitor<T> visitor);
}
// the value() Goal clashes with the interface name. 
interface Goal extends InternalValue {
Goal value();
}
}
```
After this PR, the generated class looks more like: 
```java
@Value.Enclsoing
public final MyObject {
private final InternalValue;
interface InternalValue {
<T> T accept(Visitor<T> visitor);
}
interface InternalGoalValue extends InternalValue {
Goal value();
}
}
```
> fix: union type clashes when discriminant and type are the same 

- fern-model-codegen/src/main/java/com/fern/model/codegen/enums/EnumGenerator.java
- fern-model-codegen/src/main/java/com/fern/model/codegen/union/UnionGenerator.java
- fern-model-codegen/src/main/java/com/fern/model/codegen/utils/VisitorUtils.java
- fern-model-codegen/src/test/java/com/fern/model/codegen/union/UnionGeneratorTest.java
When we use a method name we should use the MethodSpec and get the name. For visit method names, we were relying on capitalization which is error prone.
> fix: visitor references shouldn't assume camel cased discriminants

- jersey-codegen/src/main/java/com/fern/jersey/client/HttpServiceClientGenerator.java
- jersey-codegen/src/main/java/com/fern/jersey/server/HttpServiceServerGenerator.java
- utils/src/main/java/com/fern/codegen/stateless/generator/ApiExceptionGenerator.java
- utils/src/main/java/com/fern/codegen/stateless/generator/UnknownRemoteExceptionGenerator.java
- Service Client was using the wrong class name (no appended `Client`)
- UnknownRemoteException was `implementing` instead of `extending`
> fix: java compilation works

- model-codegen/src/main/java/com/fern/model/codegen/ObjectGenerator.java
Should fix generating out of order properties (resulting in failed compilation due to staged builders)
> fix: ordered map when generating object properties

- cli/src/main/java/com/fern/java/client/cli/CodeGenerationResult.java
before
```
configure(subprojects.findAll {})
```
now 
```
subprojects
```
> fix: publish all subprojects

- model-codegen/src/main/java/com/fern/model/codegen/ModelGenerator.java
previously responses were being named as requests and thus overwriting requests
> fix: generate response as part of endpoint model

- cli/src/main/java/com/fern/java/client/cli/ClientGeneratorCli.java
- cli/src/main/java/com/fern/java/client/cli/CodeGenerationResult.java
when subproject names are not accurate empty jars would get published
> fix: generate settings.gradle with accurate subproject names

- cli/Dockerfile
In order to run `./gradlew publish` we need a JDK to compile the java code
> fix: base image has jdk

- cli/src/main/java/com/fern/java/client/cli/FernPluginConfig.java
- model-codegen/src/main/java/com/fern/model/codegen/services/payloads/RequestResponseGenerator.java
- support lower case mode specification
- need to do endpointId.value() instead of endpoint +
> fix: misc bug fixes

- cli/src/eteTest/java/com/fern/java/client/cli/__snapshots__/CliEteTest.snap
- jersey-codegen/src/main/java/com/fern/jersey/server/AbstractHttpServiceRegistryGenerator.java
- previously the services were passed in via overriden methods, but the base class constructor needs to register instances so should be passed in at construction time.
> fix: abstract service registry takes in services via constructor

- cli/src/eteTest/basic/api/src/blog.yml
- cli/src/eteTest/java/com/fern/java/client/cli/__snapshots__/CliEteTest.snap
- model-codegen/src/main/java/com/fern/model/codegen/types/AliasGenerator.java
`toString` method was wrong for `Integer`, `Double`
> fix: make sure primitive aliases compile

- cli/src/eteTest/java/com/fern/java/client/cli/__snapshots__/CliEteTest.snap
- model-codegen/src/main/java/com/fern/model/codegen/types/UnionGenerator.java
Before union types would have incorrect equals/hashcode methods that wouldn't handle deep equality.
> fix: equals and hashcode on union types

- runtime-utils/jersey-utils/src/main/java/com/fern/java/jersey/expanders/OptionalExpander.java
returning "" will still cause servers to receive an empty string as the query param
> fix: optional expander returns null if optional is not present

- cli/src/eteTest/java/com/fern/java/client/cli/__snapshots__/CliEteTest.snap
- codegen-utils/src/main/java/com/fern/codegen/utils/ImmutablesUtils.java
- model-codegen/src/main/java/com/fern/model/codegen/types/UnionGenerator.java
uses `camelCase` in object property methods
> improvement: camel case properties and add JsonProperty

- generator-utils/src/main/java/com/fern/java/generators/union/UnionTypeSpecGenerator.java
For the following union 
```yaml
Age: 
years: int
second: long
```
the `getYears` method would return `Optional<int>` which would fail to compile. Now, it'll return `Optional<Integer>`.
> box primitives in subtype method

- client-generator/src/eteTest/java/com/fern/java/client/cli/__snapshots__/ClientGeneratorEteTest.snap
- client-generator/src/main/java/com/fern/java/client/generators/endpoint/WrappedRequestEndpointWriter.java
- query params are being correctly referenced from wrapper request `request.param().get()`
- non string query params are serialized as a string using `toString()`
- query param wire keys are properly serialized
> fix: misc query param bug fixes

- client-generator/src/eteTest/java/com/fern/java/client/cli/__snapshots__/ClientGeneratorEteTest.snap
- client-generator/src/main/java/com/fern/java/client/generators/endpoint/NoRequestEndpointWriter.java
- client-generator/src/main/java/com/fern/java/client/generators/endpoint/WrappedRequestEndpointWriter.java
We were previously doing `RequestBody.create("", null)` for endpoints that didn't take a request body. Now we pass `null` instead.
> fix: request body shouldnt be present in okhttp rquest

- client-generator/src/eteTest/java/com/fern/java/client/cli/__snapshots__/ClientGeneratorEteTest.snap
- client-generator/src/main/java/com/fern/java/client/generators/endpoint/AbstractEndpointWriter.java
- client-generator/src/main/java/com/fern/java/client/generators/endpoint/OnlyRequestEndpointWriter.java
- client-generator/src/main/java/com/fern/java/client/generators/endpoint/WrappedRequestEndpointWriter.java
Okhttp requires us manually sending the `Content-Type` header with `application/json`
> fix: send content type header when body is present

- client-generator/src/eteTest/java/com/fern/java/client/cli/__snapshots__/ClientGeneratorEteTest.snap
- generator-utils/src/main/java/com/fern/java/CustomConfig.java
- generator-utils/src/main/java/com/fern/java/generators/EnumGenerator.java
- generator-utils/src/main/java/com/fern/java/generators/ForwardCompatibleEnumGenerator.java
- generator-utils/src/main/java/com/fern/java/generators/SingleTypeGenerator.java
- model-generator/src/eteTest/java/com/fern/java/model/__snapshots__/ModelGeneratorEteTest.snap
- spring-server-generator/src/eteTest/java/com/fern/java/spring/__snapshots__/SpringGeneratorEteTest.snap
introduce a custom config `enable-forward-compatible-enums` which is defaulted to false. Now, by default generated enums won't have visitors and won't have an `UNKNOWN` field.
> fix: default to non forward compatible enums

- client-generator/src/eteTest/java/com/fern/java/client/cli/__snapshots__/ClientGeneratorEteTest.snap
- client-generator/src/main/java/com/fern/java/client/generators/ClientOptionsGenerator.java
The header suppliers are invoked every time  `headers()` are retrieved from `ClientOptions`. This ensures the header values are never stale.
> feature: client options supports taking in header suppliers

- client-generator/src/eteTest/java/com/fern/java/client/cli/__snapshots__/ClientGeneratorEteTest.snap
- client-generator/src/main/java/com/fern/java/client/ClientGeneratorCli.java
- client-generator/src/main/java/com/fern/java/client/GeneratedRootClient.java
- client-generator/src/main/java/com/fern/java/client/generators/RootClientGenerator.java
- client-generator/src/main/java/com/fern/java/client/generators/SampleAppGenerator.java
By generating the client builder outside of the wrapper client as a nested class, it allows sdk users to easily configure it. For example, you can add logic in the builder to do oauth2 with clientId/clientSecret.
> feature: generate client builder outside of client wrappers

- client-generator/src/eteTest/java/com/fern/java/client/cli/__snapshots__/ClientGeneratorEteTest.snap
- generator-utils/src/main/java/com/fern/java/generators/object/BuilderGenerator.java
- generator-utils/src/main/java/com/fern/java/generators/object/EnrichedObjectProperty.java
- generator-utils/src/main/java/com/fern/java/generators/object/ObjectTypeSpecGenerator.java
Literal values are now properly codegenned in objects. They are removed from the builder and are hardcoded as constant.
> feature: support literals

- generator-utils/src/main/java/com/fern/java/PoetTypeNameMapper.java
- generator-utils/src/main/java/com/fern/java/generators/AliasGenerator.java
Previously, datetimes were generated as unparsed strings but now they are generated as `OffsetDatetime` in java.
> feature: datetimes are generated as `java.Time.OffsetDatetime`

- client-generator/src/eteTest/java/com/fern/java/client/cli/__snapshots__/ClientGeneratorEteTest.snap
- client-generator/src/main/java/com/fern/java/client/generators/endpoint/WrappedRequestEndpointWriter.java
Only populate request body properties if they are present.
> :herb: only add wrapped request fields if present

- client-generator/src/eteTest/java/com/fern/java/client/cli/__snapshots__/ClientGeneratorEteTest.snap
- client-generator/src/main/java/com/fern/java/client/ClientGeneratorCli.java
- client-generator/src/main/java/com/fern/java/client/generators/RequestOptionsGenerator.java
Generate a RequestOptions class that can be used to override auth and headers in the client.
> feature: generate a `RequestOptions` class 

- client-generator/src/eteTest/java/com/fern/java/client/cli/__snapshots__/ClientGeneratorEteTest.snap
- client-generator/src/main/java/com/fern/java/client/ClientGeneratorCli.java
- client-generator/src/main/java/com/fern/java/client/generators/ClientGeneratorUtils.java
- client-generator/src/main/java/com/fern/java/client/generators/ClientOptionsGenerator.java
- client-generator/src/main/java/com/fern/java/client/generators/RootClientGenerator.java
- client-generator/src/main/java/com/fern/java/client/generators/SubpackageClientGenerator.java
- client-generator/src/main/java/com/fern/java/client/generators/endpoint/AbstractEndpointWriter.java
- client-generator/src/main/java/com/fern/java/client/generators/endpoint/HttpEndpointMethodSpecFactory.java
- client-generator/src/main/java/com/fern/java/client/generators/endpoint/HttpEndpointMethodSpecs.java
- client-generator/src/main/java/com/fern/java/client/generators/endpoint/NoRequestEndpointWriter.java
- client-generator/src/main/java/com/fern/java/client/generators/endpoint/OnlyRequestEndpointWriter.java
- client-generator/src/main/java/com/fern/java/client/generators/endpoint/WrappedRequestEndpointWriter.java
Each endpoint is overloaded with request options so that the user can specify RequestOptions if they want to, but don't have to.
> fix: endpoints are overloaded and use request options

- client-generator/src/eteTest/java/com/fern/java/client/cli/__snapshots__/ClientGeneratorEteTest.snap
- client-generator/src/main/java/com/fern/java/client/generators/ClientOptionsGenerator.java
The generated java sdk will now send fern platform headers `X-Fern-SDK-Name`, `X-Fern-SDK-Version`, and `X-Fern-SDK-Language`. These headers will make it easy for users to track requests made through fern generated SDKs.
> fix: generated java sdk sends fern platform headers

- client-generator/src/main/java/com/fern/java/client/generators/endpoint/WrappedRequestEndpointWriter.java
- seed/file-upload/src/main/java/com/seed/fileUpload/resources/service/ServiceClient.java
Previously any multipart file uploads were being sent with an `application/json` content type header.
> fix: file upload should not be sent with `application/json` Content-Type

- README.md
- client-generator/src/main/java/com/fern/java/client/ClientGeneratorCli.java
- client-generator/src/main/java/com/fern/java/client/JavaSdkCustomConfig.java
- generator-utils/src/main/java/com/fern/java/AbstractGeneratorCli.java
- generator-utils/src/main/java/com/fern/java/output/gradle/AbstractGradleDependency.java
- generator-utils/src/main/java/com/fern/java/output/gradle/GradleDependencyType.java
- generator-utils/src/main/java/com/fern/java/output/gradle/ParsedGradleDependency.java
- generator-utils/src/main/java/com/fern/java/output/gradle/RootProjectGradleDependency.java
- generator-utils/src/test/java/com/fern/java/output/GeneratedBuildGradleTest.java
- model-generator/src/main/java/com/fern/java/model/ModelGeneratorCli.java
- spring-server-generator/src/main/java/com/fern/java/spring/SpringGeneratorCli.java
z- Add a custom config to support adding arbitrary dependencies to the Java SDK
```yaml
config:
custom-dependencies: 
- "implementation com.foo:bar:0.0.0"
- "testImplementation com.foo:bar:0.0.0"
- "api com.foo:bar:0.0.0"
```
> fix: support custom dependencies

- client-generator/src/main/java/com/fern/java/client/generators/WrappedRequestGenerator.java
- generator-utils/src/main/java/com/fern/java/generators/ObjectGenerator.java
- generator-utils/src/main/java/com/fern/java/output/GeneratedObject.java
- generator-utils/src/main/java/com/fern/java/output/gradle/AbstractGradleDependency.java
The java SDK was previously not sending request body properties that were inherited.
> fix: sdk sends request body properties that are inherited

- generator-utils/src/main/java/com/fern/java/generators/object/EnrichedObjectProperty.java
- generator-utils/src/main/java/com/fern/java/utils/KeyWordUtils.java
Right now we have a list of reserved variables that we use to special case class variables, however we don't do the same for getters
I chose to just use the same reserved name list, but we might want to consider a reserved function name list instead (I just couldn't find one online), curious your take @dsinghvi 
I build a small test that seems to solve the issue Metriport is running into
```
types:
BaseObject:
properties:
prop1: string
prop2: string
Account:
properties: 
class: BaseObject
package: BaseObject
```
> [fix] treat getters of reserved words special as well
